#!/bin/bash
set -eu

if [ "$#" -eq 0 ]
then
  echo "No arguments supplied"
  exit 1
fi

file="$(realpath "$1")"
cd "$(dirname "$0")"
# cat "$file" | opam exec -- dune exec katex_pp
cat "$file" | ./_build/default/bin/main.exe 
